### ISSUE TITLE
how to turn off "x requested a mash of 144 updates" messages

### ISSUE THREAD

**Issue by agrover** [fedora-infra/fmn#103]
Looking at my enabled notifications and searching for "mash", it is not obvious what rule to turn off to stop getting these messages.

**Comment by ralphbean** [comment]
Oh, shoot.  We don't have a rule for it yet that you could use to rule out those messages.  We'll need to add it to the [fmn.rules repository](https://github.com/fedora-infra/fmn.rules).

(FWIW, we likely want to add an alembic upgrade script in [fmn.lib](https://github.com/fedora-infra/fmn.lib) as well that automatically adds that new rule to everyone's existing filters, since (especially when we're still working out kinks in the masher) it can be quite spammy).
