### ISSUE TITLE
Support for Anitya at release-monitoring.org

### ISSUE THREAD

**Issue by grahamwhiteuk** [fedora-infra/fmn#1058]
My old FMN seem to have stopped working (getting a 503 error from that application) and the new FMN doesn't support Anitya.  This is my main use case for FMN.

As a packager I would like to be notified about new releases of packages I maintain so that I can produce new package versions in a timely manner.

**Comment by grahamwhiteuk** [comment]
BTW... wondering if anyone has/is already working on this?  If not, I can look into contributing a PR assuming the maintainers here are willing to merge and deploy such a change?

**Comment by abompard** [comment]
Hey! Anitya should be supported already. I can look into why you don't get notifications, what's your Fedora username? Thanks.

**Comment by grahamwhiteuk** [comment]
My FAS ID is `grahamwhiteuk`

**Comment by abompard** [comment]
Ah, it looks like you don't have any rules at the moment. There aren't any default rules in the new FMN (that's issue #900), so you'll need to at least create a rule with the tracking rule named "My Events". It's at https://notifications.fedoraproject.org.

**Comment by grahamwhiteuk** [comment]
Aha... I hadn't realised Anitya would be listed under "My Events".  I think I'm a victim of poor UX.  I've configured a rule so I'll see if that works out, thanks for the pointer.

**Comment by lantw44** [comment]
I have an Anitya rule under My Events enabled for months, but I never ever get a single message from it. The topic pattern is set to `*`, so there should be no filter. It seems to me that the My Events tracking rule causes all messages to be dropped since Anitya messages are unrelated to any user or artifact.

If this is true, is it possible to have a way to add a rule without a tracking rule or a special tracking rule for Anitya?

**Comment by abompard** [comment]
Hey @lantw44 , if I understand correctly, I think this PR should help: https://github.com/fedora-infra/anitya-messages/pull/70

**Comment by lantw44** [comment]
@abompard Thank you. I got 2 messages from Anitya with the Artifacts tracking rule this week.
