### ISSUE TITLE
Pagure notifications missing namespace

### ISSUE THREAD

**Issue by athos-ribeiro** [fedora-infra/fmn#141]
Emails are being sent without gropup namespaces, whenever they are present.

Example: I added a comment ambassadors-latam/tasks

Pagure sends me an email linking to https://pagure.io/ambassadors-latam/tasks/issue/364#comment-46479

But fmn sends me an email linking to https://pagure.io/tasks/issue/364#comment-46479

Looking closer, it seems we may have a problem on fmn/rules/pagure.py:38. Sorry for not looking deeper into it.

**Comment by pypingou** [comment]
This was a bug in fedmsg_meta which has been fixed in https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/pull/409 it has been released on Friday and pushed to prod yesterday iirc.

So we should be all good here, therefore I'm going to close this ticket, please re-open if you see it again :)
