### ISSUE TITLE
Create a fedmsg backend

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#178]
On the face of it, this sounds a little silly, but...

It would be convenient for some services (for example, Fedora Hubs) to consume fedmsgs that represent notifications for users and groups. We could introduce a fedmsg backend that emits fedmsgs that represent the processed incoming message. These would include the human-readable text and the recipients of the message (FAS user/group).

The motivation for Hubs specifically is that the SSE server for groups is, as far as we can tell, untenable. The RabbitMQ would be drained when the first user in a group consumes the SSE messages and then other users wouldn't see any notifications. Even with users, after they initially receive the SSE, they won't get any more when they refresh the page or something. I hear you can sort of cache things locally with JavaScript, but I'm not sure and we still have the issue with groups. With fedmsgs, the Hubs server could cache these notifications for groups/users.

To do this, we also need to add a piece to the fedmsg consumer so it filters out messages from the backend so we don't get a nasty positive feedback loop.

Feedback/thoughts welcome, this is something @abompard and I talked about briefly in IRC. I'd specifically be interested in hearing what @pypingou thinks about this.

**Comment by pypingou** [comment]
The SSE was an answer to the original work that was replicated FMN's logic into hubs itself. It may not be a perfect solution (and I think you found holes in it), so it may make more sense to go a different route.

My only question regarding this idea is: does it make sense to keep the SSE server then? From a maintenance point of view, having just one system (the fedmsg backend) to maintain instead of two (fedmsg + SSE) may be a good thing, so I'd encourage that we test the capabilities of the fedmsg backend and if we can make it work for all the use-cases of hubs, sounds like a win to me :)

**Comment by jeremycline** [comment]
I certainly don't think we need to run it in production (unless someone has a use-case for it), but we could keep it around without much harm, I think.

**Comment by pypingou** [comment]
👍 on keeping the code since we may want to reuse it or part of it at one point, my "keeping" should have been "running" I guess, ie: do we want to run both or can we port everything to a fedmsg backend? (with a preference for the later)

**Comment by jeremycline** [comment]
I think we can port everything to a fedmsg backend and not run the SSE backend

**Comment by pypingou** [comment]
Cool :)

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
