### ISSUE TITLE
Ratelimit requeueing

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/fmn#188]
It would be very useful if we can ratelimit the requeueing, so we don't retry the exact same message 500 times a minute.
An idea for this would be to add extra fields when we requeue a message with "num_requeues" and "ignore_until".
We can set "ignore_until" to time.time() + min(3600, 2^num_requeues) or something (aka, exponential backoff), and num_requeues is get(num_requeues, 0)+1.

Then if we get a message with an ignore_until < time.time(), we just silently put it back in the queue (without changing num_requeues or ignore_until!) and go back to the queue.

**Comment by jeremycline** [comment]
Libraries like Celery will let you define [task retry mechanisms](http://docs.celeryproject.org/en/latest/userguide/tasks.html#retrying). We should use something like that rather than trying to re-invent that wheel.

I outlined several options for re-writing FMN in #170 that include using Celery as a task system.

**Comment by jeremycline** [comment]
This is very nearly all solved, except for one special case in the IRC backend (see #249)
