### ISSUE TITLE
FMN doesn't deliver messages through matrix-irc bridge

### ISSUE THREAD

**Issue by igor-raits** [fedora-infra/fmn#217]
After I switched for IRC to use Matrix, I stopped getting any fedmsg notifications which is weird..

@nirik suggested to open ticket here one day.u

**Comment by jeremycline** [comment]
This is odd. I'm able to send PMs to my Matrix user via IRC, but notifications definitely don't arrive. I'm not sure what the cause is, exactly.

**Comment by igor-raits** [comment]
I think https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#why-i-dont-get-messages-from-unregistered-to-irc-irc-users might explain why I don't receive those notifications...

TL;DR; matrix doesn't allow unregistered users to send PMs

**Comment by igor-raits** [comment]
@jeremycline cool! has this been deployed in prod already? If not, when?

Missing notifications for very long time already!

**Comment by jeremycline** [comment]
I was thinking of kicking it out to stage tomorrow. I can ping you when that happens. Infra is in freeze at the moment so it may be a little while until it's in prod, but I don't think it'll be hard to get a freeze exception since FMN doesn't really work right now anyway.

As a work-around you could just use stage since until the fix is in prod since it gets all the production fedmsgs.

**Comment by jeremycline** [comment]
This is now in [staging](https://apps.stg.fedoraproject.org/notifications/) and I can get notifications with +R set again so it should also work with Matrix assuming you've also authenticated with nickserv.
