### ISSUE TITLE
Revisit the defaults

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn#29]
The default preferences need to be looked over again.  If you have a suggestion for what they should or shouldn't include, please list it here:

**Comment by ralphbean** [comment]
From dgilmore:
- By default we should not send notifications for koji tasks starting, we should only second secondary arch koji notifications for failed tasks to the maintainers. all tagging into and out of secondary arch tags that have SHADOWBUILD in the tag name should be ignored possibly all secondary arch tagging, It's part of the secondary arch buildroot mirroring process and creates a lot of events. 
- Meeting topic changes should not have notifications sent.

**Comment by bochecha** [comment]
I just edited a ticket in the rel-eng trac, and got an FMN notification for it.

It would be great if by default FMN could notify all stakeholders of a given ticket **except** the person making the modification.

A bit like Bugzilla excludes the person making a comment on a bug report, even if that person is CC-ed to it.

**Comment by tomhughes** [comment]
What @bochecha says is, to my mind, a general problem. I'm currently trying to figure out how to change many of the default filters so that they will only tell me about things other people do and not things I do - if I push to git for one of my packages then I already know about it and don't need to be told, but if somebody else does then I would like to know for example.

In many cases it's not clear if it's even possible (it mostly comes down I think to understanding what constitutes being "associated" with a given user for each message type) and it's certainly not easy.

It should certainly be possible to easily exclude self-triggered messages, and I would suggest it should probably be the default.

**Comment by pypingou** [comment]
> It should certainly be possible to easily exclude self-triggered messages, and I would suggest it should probably be the default.

It would be pretty easy to do, but the idea of notifying about action you do is that you then have a chance to find out (pretty easily) if someone steal your account and uses it.

**Comment by tomhughes** [comment]
Well the reality is that it just generates so much noise that I just delete all fed notification emails pretty much unread, so if that is the goal then it is not being met.
