### ISSUE TITLE
RFE: Add severity level to messages, ability to filter by severity level

### ISSUE THREAD

**Issue by jwrdegoede** [fedora-infra/fmn#301]
Hi,

As discussed here:  https://pagure.io/fesco/issue/1947

Properly using the filtering in FMN atm is quite hard to do. The problem is that the filtering is too fine grained and I personally have given up on filtering instead just shoving all mails from notifications@fedoraproject.org into a mail-folder which I check maybe once a month.

This means that important messages may get unnoticed for a long time. IMHO it would be better if notifications would come with a severity level and most, such as e.g. a build succeeding, or some changes being committed,  would have a level of info/normal. But e.g. a build failure would get a level of warning and e.g. a depcheck or abicheck failure would get a level of  error.

This would then be combined with an option to filter on the severity level, which will give users a simple way to say only give me warning messages, This also has the big advantage that users do not need to tweak their filters as new messages are introduced.

Regards,

Hans

**Comment by jeremycline** [comment]
> Properly using the filtering in FMN atm is quite hard to do. The problem is that the filtering is too fine grained and I personally have given up on filtering instead just shoving all mails from notifications@fedoraproject.org into a mail-folder which I check maybe once a month.

Agreed. I'd prefer it if we made something that offered a small number of options and worked well for *most* users. I don't think any amount of UI redesign on top of the current filtering rules will make it usable.

> This means that important messages may get unnoticed for a long time. IMHO it would be better if notifications would come with a severity level and most, such as e.g. a build succeeding, or some changes being committed, would have a level of info/normal. But e.g. a build failure would get a level of warning and e.g. a depcheck or abicheck failure would get a level of error.

I like this idea. One issue on the fesco ticket was who sets the severity level, but I think that the app developers should be able to set it on the messages they send with reasonable accuracy. A build failure is in warning/error territory. CI passing is informational, failing is warning/error. I'm sure there will be disagreement about what the right severity level is for a message, but I'd rather have that than what we've got right now.

> This would then be combined with an option to filter on the severity level, which will give users a simple way to say only give me warning messages, This also has the big advantage that users do not need to tweak their filters as new messages are introduced.

Yep, the current default filters (which I assume most people use because changing them is crazy) boil down:

* Messages related to packages (ones you have ACLs on) with a bunch of filters to remove low severity ones

* Events about a username (yours) with a bunch of filters to remove low severity ones.

If every message contained a severity level, as well as a list of users and packages it related to, we could delete most of FMN which would make me very happy. The UI could be super simple, too. Just ask for a list of packages and users (default to your packages and name) with a severity.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
