### ISSUE TITLE
Email without a filter

### ISSUE THREAD

**Issue by bochecha** [fedora-infra/fmn#41]
Yesterday evening, I received this email from FMN:

```
An anonymous user gave gthumb a rating of 100
        https://apps.fedoraproject.org/tagger/gthumb

--
You received this message due to your preference settings at
https://apps.fedoraproject.org/notifications//bochecha.id.fedoraproject.org/email/10066
```

I'm not interested in that, so I thought I'd go and click that link, to change the filter.

But the link gives me back a 404.

And in my list of filters (which should be the default ones, afaik), there indeed is no 10066. (it jumps between 10065 and 10068)

I also see no filter related to Tagger. :confused: 

So it seems the email is wrong on the filter URL, and there doesn't seem to be a way to not receive this kind of notifications any more?

**Comment by pypingou** [comment]
Could the filter have been dropped when we cleaned the DB after the upgrade?

**Comment by ralphbean** [comment]
@pypingou has it.  There was a fudged DB upgrade yesterday that left some filters in a half-removed state.  Lots of emails made it out to people that shouldn't have.

Long story -> you had a filter to show you messages about packages you own being retired.  It had two rules:
- Show me notifs on packages that I own.
- Show me notifs of people retiring packages.

The second one got renamed/removed, but the first one stayed.  You were left with a filter that simply forwarded you all messages that mention packages that you own.  It took an hour or so before we realized it, and deleted that hanging filter all-together.  This affected all FMN users.

I'm going to go ahead and close this since it is fixed in git and the production DB.  Sincere apologies for the spam, and thanks for reporting it.  :(
