### ISSUE TITLE
Add ability to select which tag for 'packages added to koji tag' and 'packages removed from koji tag'

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fmn#75]
I don't see a way to specify a tag on those items and it could be handy, for example, you could make a filter that was: 

package is kernel
packages added to koji tag f23

and it would only tell you when a f23 kernel build was completed. 
Or

package foo
packages added to koji tag f22-updates

would tell you when package foo is moving into the updates repo. 

I guess it may need to be a dropdown list?

**Comment by ralphbean** [comment]
I figured this would be easy to implement... but when testing I realized that we're currently dropping all koji tag messages from any FMN considerations for performance reasons.  They come in those huge 200 message/second spikes and we figured no one wanted to know about them anyways.  See the `junk_suffixes` setting here:  https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/notifs/backend/templates/fmn.consumer.py#n58

It's now a question of "how important is this"?  If it is less important, I'd like to punt and solve another day.  If it is more important, we'll have to first put more optimization work into the core fmn stuff so that it can handle that new volume of messages.  After that, the patch to add a rule to match these kinds of messages is simple.

``` diff
diff --git a/fmn/rules/buildsys.py b/fmn/rules/buildsys.py
index 8ae130a..3195bf9 100644
--- a/fmn/rules/buildsys.py
+++ b/fmn/rules/buildsys.py
@@ -226,15 +226,37 @@ def koji_repo_init(config, message):

 @hint(topics=[_('buildsys.tag')])
 def koji_tag(config, message):
-    """ Packages are added to a Koji tag
+    """ Packages are added to any Koji tag

     This rule lets through messages that get published when the `koji build
-    system <http://koji.fedoraproject.org>`_ applies a certain tag to a
-    package.
+    system <http://koji.fedoraproject.org>`_ applies a tag to a package.
     """
     return message['topic'].endswith('buildsys.tag')


+@hint(topics=[_('buildsys.tag')], invertible=False)
+def koji_particular_tag(config, message, tagnames=None):
+    """ Packages are added to a particular Koji tag
+
+    This rule lets through messages that get published when the `koji build
+    system <http://koji.fedoraproject.org>`_ applies **a particular tag** to a
+    package, letting you specify which tags you're interested in.  Tag names
+    may be comma-separated.
+
+    For example, you might specify ``rawhide,f22-updates-testing`` if you want
+    to know when things are tagged into either rawhide or f22-updates-testing.
+    """
+    if not koji_tag(config, message):
+        return False
+
+    target = message['msg']['tag']
+    tagnames = tagnames or ''
+    for name in tagnames.split(','):
+        if name.strip() == target:
+            return True
+    return False
+
+
 @hint(topics=[_('buildsys.untag')])
 def koji_untag(config, message):
     """ Packages are removed from a Koji tag
```

**Comment by nirik** [comment]
Yeah, I don't know how urgent it is, but it might be nice... 

The tags do come in floods... could we ignore them in irc and otherwise still get them? Or that would cause problems too?

**Comment by mizdebsk** [comment]
:+1: I would also be interested in seeing this implemented.

**Comment by ralphbean** [comment]
Now that we have the newly refactored backend in place, the optimization issue is partly resolved.

We could look at trying this again.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
