### ISSUE TITLE
Add a noscript tag to index.html for browsers with Javascript disabled

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fmn#889]
The noscript tag should explain that Javascript is required to run the UI.

**Comment by Ayesh-07** [comment]
Dear Abompard,
I hope this message finds you well. I'm reaching out regarding the project issue #889 . Having reviewed the details, I'm confident that I can efficiently contribute to resolving this matter. Would you kindly consider assigning this issue to me?

**Comment by gridhead** [comment]
@Ayesh-07, have at it.

**Comment by Ayesh-07** [comment]
What should I have to do.. For pull request. Please guide me I was working
on it past 2 days.. I'm bigginer struggling for making myself good.


1. Create a folder then open it in vs. Code
2. Fork the open source project
3.clone a project from fork file
4. Git init
5.make a branch addnoscript#889
6. Make changing in index. html file
7. Add and commit changing
8. Push project into develop (main branch)

Project default master/ main branch is develop.

What should I have to do.. For pull request. Please guide me

**Comment by gridhead** [comment]
@Ayesh-07 you need not initialize a repository again if you are cloning a fork of the said project. Also, please make changes to a non-primary branch so that you can have the former to roll back to, should things mess up.

Here are some resources that can help you get started with this issue ticket.

1. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript
2. https://www.w3schools.com/tags/tag_noscript.asp
3. https://en.wikipedia.org/wiki/NoScript

**Comment by Ayesh-07** [comment]
Thank you for your invaluable guidance with the problem. Your expertise and
support have been immensely helpful, and I truly appreciate the time and
effort you've dedicated to helping me.

Best regards,
[Ayesha
