### ISSUE TITLE
Add email header if notification is coming from a pkgdb group

### ISSUE THREAD

**Issue by crobinso** [fedora-infra/fmn#98]
This comes from some discussion here: https://fedorahosted.org/fedora-infrastructure/ticket/4778#comment:3

It would be nice to be able to filter out differences between notifications I receive for user=crobinso and notifications I receive for group=virtmaint-sig. We worked around it for my particular case by doing 'commit acl' instead of 'any acl' watch, but that's not ideal in the generic case since I can't watchbugzilla/watchcommit for arbitrary packages now.

So maybe the notifications system can add an email header when I'm receiving a notification strictly through my group membership?

**Comment by opoplawski** [comment]
I'm faced with a similar (same) issue - getting lots of commit messages for python-sig group commit watches and I really don't want to receive them.  I'm not sure a header would help in my case because I receive digest mails which might have multiple notices from different packages grouped together.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
