### ISSUE TITLE
Spawn subprocesses instead of threads

### ISSUE THREAD

**Issue by mizdebsk** [fedora-infra/fmn#99]
FMN deployed at Fedora infrastructure [drops certain kinds of messages](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/notifs/backend/templates/fmn.consumer.py?id=bfc995c0c4ef1f4730a956f11a41effbda2cd92d#n62) (such as Koji tag/untag messages) due to performance problems, which according to @ralphbean are caused by Python global interpreter lock.

Proposed solution is to use subprocesses instead of (or in addition to) threads to workaround limitations of Python threading.

**Comment by ralphbean** [comment]
It gets tricky fast.
- the fmn backend is running as a twisted reactor with open irc and smtp and database connections.  Early on I tried simply forking the process but that was a disaster.
- a fan-out work queue is attractive because of how we can just add more workers if we become overloaded.
- it gets tricky though because the expensive part of the process is where we match messages to users by running all the _rules_.  once we decide who gets the message, we need to actually send them which is light weight, but stateful.  We need a single process that maintains a single IRC connection so that people don't get their messages from a variety of irc nick.. just from a single irc nick.  To solve this, we'll need a fan out process _and_ a fan in at the end.

**Comment by ralphbean** [comment]
Hm, does FMN fan out and fan in now with the celery refactor?

**Comment by jeremycline** [comment]
Yup. It's still _really_ slow, but we do have the option to throw a ton of workers at the problem now. At the moment each worker handles a message ever 2 seconds (oof, I know) and we have 4 workers. This is fine since the current messages per second is rarely higher than 2.

Long term all the message topics should become more useful (get more specific) and then FMN would really just be "give me a list of topics you want" and that is used to make a queue in AMQP with those subscription options. Load all that work off onto the broker.

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore. 

Closing, but reopen if you feel this still applies.
